### ISSUE TITLE
Improve error checking

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/pybaum#2]
## To-Do

- [ ] Add explicit error handling to `tree_equal`
- [ ] Check for typos in `options` and `types` in `get_registry` and suggest improvements with fuzzywuzzy
- [ ] Look for more places where we need better error handling
