### ISSUE TITLE
Add basic documentation

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/pybaum#6]
## To-Do

- [ ] Add all functions that can be directly imported from pybaum to an API Documentation
- [ ] Write some text about the rationale behind pybaum
- [ ] Explain deviations from JAX
- [ ] Add examples
